version: 1.0

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running unit tests...
      - python3 -m unittest test_app.py
artifacts:
  files:
    - app.py
    - requirements.txt
    - run.sh
    - stop.sh
    - appspec.yml
  name: output-artifact
